const SIMPLE_SPREADSHEET_ID='1z2vVKOAuIiDvYXzIcY4nl-vARVaTb_PC-EsWN294NeM';
const ST={EMP:'NHAN_VIEN',DEP:'PHONG_BAN',KPI:'DANH_MUC_KPI',ROLE:'KPI_THEO_VI_TRI',ASN:'GIAO_CHI_TIEU',ALLOC:'PHAN_BO_KPI',PERF:'THUC_HIEN_KPI',RES:'KET_QUA_KPI',CFG:'CAU_HINH',LOG:'NHAT_KY_HE_THONG',P3:'CAU_HINH_3P',PAY:'BANG_LUONG'};
function doGetSimple(){return HtmlService.createTemplateFromFile('Index').evaluate().setTitle('CT Food KPI')}
function includeSimple(n){return HtmlService.createHtmlOutputFromFile(n).getContent()}
function sss_(){return SpreadsheetApp.openById(SIMPLE_SPREADSHEET_ID)}
function srows_(n){const s=sss_().getSheetByName(n);if(!s)return[];const v=s.getDataRange().getValues();if(v.length<2)return[];const h=v[0].map(String);return v.slice(1).filter(r=>r.some(x=>x!==''&&x!=null)).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]])))}
function sper_(v){return v instanceof Date?Utilities.formatDate(v,'Asia/Ho_Chi_Minh','yyyy-MM'):String(v||'')}
function sconfig_(){return Object.fromEntries(srows_(ST.CFG).map(x=>[x.KEY,x.VALUE]))}
function scurrentPeriod_(){const v=sconfig_().CURRENT_PERIOD;return sper_(v)||Utilities.formatDate(new Date(),'Asia/Ho_Chi_Minh','yyyy-MM')}
function scurrentUser_(){const e=String(Session.getActiveUser().getEmail()||'').toLowerCase();if(!e)throw Error('Không xác định được email Google. Cần triển khai Web App với quyền truy cập phù hợp Google Workspace.');const u=srows_(ST.EMP).find(x=>String(x.Email||'').toLowerCase()===e&&String(x['Trạng thái']||'ACTIVE')!=='NGHI_VIEC');if(!u)throw Error('Email '+e+' chưa có trong NHAN_VIEN');return u}
function sscope_(u,e){const r=String(u['Vai trò hệ thống']||'EMPLOYEE');return ['ADMIN','BOARD','EXECUTIVE'].includes(r)||r==='MANAGER'&&String(e.DEPARTMENT_ID)===String(u.DEPARTMENT_ID)||String(e.EMPLOYEE_ID)===String(u.EMPLOYEE_ID)}
function getSimpleAppData(){const u=scurrentUser_(),p=scurrentPeriod_(),es=srows_(ST.EMP).filter(e=>sscope_(u,e)),ids=new Set(es.map(e=>String(e.EMPLOYEE_ID))),as=srows_(ST.ASN).filter(a=>sper_(a.PERIOD_ID)===p&&ids.has(String(a.ASSIGNEE_ID))),rs=srows_(ST.RES).filter(r=>sper_(r.PERIOD_ID)===p&&ids.has(String(r.EMPLOYEE_ID))),pf=srows_(ST.PERF).filter(r=>sper_(r.PERIOD_ID)===p&&ids.has(String(r.EMPLOYEE_ID)));const done=rs.filter(x=>x['% Hoàn thành']!==''&&x['% Hoàn thành']!=null);return{user:u,period:p,employees:es,assignments:as,results:rs,performance:pf,departments:srows_(ST.DEP),kpis:srows_(ST.KPI),roleKpis:srows_(ST.ROLE),income:simpleIncome_(u,p,rs),summary:{score:rs.reduce((s,x)=>s+Number(x['Điểm quy đổi']||0),0),completion:done.length?done.reduce((s,x)=>s+Number(x['% Hoàn thành']||0),0)/done.length:0,active:as.filter(x=>String(x['Trạng thái'])!=='DA_CHOT').length,closed:as.filter(x=>String(x['Trạng thái'])==='DA_CHOT').length}}}
function saveSimplePerformance(d){const u=scurrentUser_(),a=srows_(ST.ASN).find(x=>String(x.ASSIGNMENT_ID)===String(d.assignmentId));if(!a||String(a.ASSIGNEE_ID)!==String(u.EMPLOYEE_ID))throw Error('KPI không thuộc người dùng');if(String(a['Trạng thái'])==='DA_CHOT')throw Error('KPI đã chốt');const id='PERF-'+Utilities.getUuid().slice(0,8).toUpperCase();sappend_(ST.PERF,{RECORD_ID:id,PERIOD_ID:sper_(a.PERIOD_ID),'Ngày':d.date||Utilities.formatDate(new Date(),'Asia/Ho_Chi_Minh','yyyy-MM-dd'),EMPLOYEE_ID:u.EMPLOYEE_ID,'Nhân viên':u['Họ tên'],ASSIGNMENT_ID:a.ASSIGNMENT_ID,'Mã KPI':a['Mã KPI'],'Tên KPI':a['Tên KPI'],'Giá trị thực hiện':Number(d.value),'Đơn vị':a['Đơn vị'],'Minh chứng/Link':d.evidence||'','Ghi chú':d.note||'','Trạng thái':'DA_GUI'});return{ok:true,id}}
function sappend_(n,o){const s=sss_().getSheetByName(n),h=s.getRange(1,1,1,s.getLastColumn()).getValues()[0];s.appendRow(h.map(k=>Object.prototype.hasOwnProperty.call(o,k)?o[k]:''))}

function simpleIncome_(u,p,rs){const pay=srows_(ST.PAY).find(x=>sper_(x.PERIOD_ID)===p&&String(x.EMPLOYEE_ID)===String(u.EMPLOYEE_ID));if(!pay)return null;const cs=srows_(ST.P3).filter(x=>String(x['Trạng thái'])==='ACTIVE'),cc=cs.find(x=>String(x['Phạm vi'])==='EMPLOYEE'&&String(x['Đối tượng'])===String(u.EMPLOYEE_ID))||cs.find(x=>String(x['Phạm vi'])==='POSITION'&&String(x['Đối tượng'])===String(u['Chức danh']))||cs.find(x=>String(x['Phạm vi'])==='DEFAULT');return cc?{target:pay['Lương KPI mục tiêu'],p1:cc['Tỷ lệ 1P'],p2:cc['Tỷ lệ 2P'],p3:cc['Tỷ lệ 3P'],score:rs.reduce((s,x)=>s+Number(x['Điểm quy đổi']||0),0)}:null}
function simpleAcceptAssignment(id){const u=scurrentUser_(),a=srows_(ST.ASN).find(x=>String(x.ASSIGNMENT_ID)===String(id));if(!a||String(a.ASSIGNEE_ID)!==String(u.EMPLOYEE_ID))throw Error('KPI không thuộc người dùng');if(String(a['Trạng thái'])!=='DA_GIAO')return{ok:true,status:a['Trạng thái']};supdate_(ST.ASN,'ASSIGNMENT_ID',id,{'Trạng thái':'DA_NHAN'});slog_(u.EMPLOYEE_ID,'NHAN_KPI',ST.ASN,id,'DA_GIAO','DA_NHAN');return{ok:true,status:'DA_NHAN'}}
function simpleConfirmPerformance(id,approved){const u=scurrentUser_(),role=String(u['Vai trò hệ thống']);if(!['ADMIN','BOARD','EXECUTIVE','MANAGER'].includes(role))throw Error('Không có quyền xác nhận');const rec=srows_(ST.PERF).find(x=>String(x.RECORD_ID)===String(id));if(!rec)throw Error('Không tìm thấy kết quả');const emp=srows_(ST.EMP).find(x=>String(x.EMPLOYEE_ID)===String(rec.EMPLOYEE_ID));if(!emp||!sscope_(u,emp))throw Error('Ngoài phạm vi quản lý');const st=approved?'DA_XAC_NHAN':'TU_CHOI';supdate_(ST.PERF,'RECORD_ID',id,{'Trạng thái':st,'Người xác nhận':u['Họ tên'],'Thời gian xác nhận':new Date()});if(approved)srecalc_(String(rec.ASSIGNMENT_ID));slog_(u.EMPLOYEE_ID,approved?'XAC_NHAN_KET_QUA':'TU_CHOI_KET_QUA',ST.PERF,id,rec['Trạng thái'],st);return{ok:true,status:st}}
function simpleCreateAssignment(d){const u=scurrentUser_(),role=String(u['Vai trò hệ thống']);if(!['ADMIN','BOARD','EXECUTIVE','MANAGER'].includes(role))throw Error('Không có quyền giao KPI');const emp=srows_(ST.EMP).find(x=>String(x.EMPLOYEE_ID)===String(d.employeeId));if(!emp||!sscope_(u,emp))throw Error('Ngoài phạm vi quản lý');const rk=srows_(ST.ROLE).find(x=>String(x['Đơn vị/Vị trí'])===String(d.position)&&String(x['Mã KPI'])===String(d.kpiCode));if(!rk)throw Error('KPI không thuộc vị trí đã chọn');if(rk['Target mặc định']===''||rk['Target mặc định']==null)throw Error('Target KPI đang chờ phê duyệt');const master=srows_(ST.KPI).find(x=>String(x['Mã KPI'])===String(d.kpiCode))||{},p=scurrentPeriod_(),id='ASN-'+p+'-'+emp.EMPLOYEE_ID+'-'+d.kpiCode;if(srows_(ST.ASN).some(x=>String(x.ASSIGNMENT_ID)===id))throw Error('KPI đã được giao trong kỳ');sappend_(ST.ASN,{ASSIGNMENT_ID:id,PARENT_ASSIGNMENT_ID:d.parentId||'',PERIOD_ID:p,'Kỳ':p,'Cấp giao':role==='MANAGER'?'TRUONG_PHONG':'BĐH',ASSIGNER_ID:u.EMPLOYEE_ID,'Người/Đơn vị giao':u['Họ tên'],'Cấp nhận':'NHAN_VIEN',ASSIGNEE_ID:emp.EMPLOYEE_ID,'Người/Đơn vị nhận':emp['Họ tên'],DEPARTMENT_ID:emp.DEPARTMENT_ID,'Phòng ban':emp['Phòng ban'],'Mã KPI':d.kpiCode,'Tên KPI':rk['Tên KPI'],'Đơn vị':master['Đơn vị']||'','Chiều':master['Chiều']||'Tăng',Target:d.target===''||d.target==null?rk['Target mặc định']:Number(d.target),'Trọng số %':Number(rk['Trọng số mặc định %']||0),'Ngày giao':new Date(),'Nguồn KPI':'KPI_THEO_VI_TRI','Quy tắc phân bổ':'SUM_EXACT','Trạng thái':'DA_GIAO'});slog_(u.EMPLOYEE_ID,'GIAO_KPI',ST.ASN,id,'','DA_GIAO');return{ok:true,id}}
function srecalc_(aid){const a=srows_(ST.ASN).find(x=>String(x.ASSIGNMENT_ID)===aid);if(!a)return;const ps=srows_(ST.PERF).filter(x=>String(x.ASSIGNMENT_ID)===aid&&String(x['Trạng thái'])==='DA_XAC_NHAN'),actual=ps.reduce((s,x)=>s+Number(x['Giá trị thực hiện']||0),0),blank=a.Target===''||a.Target==null,target=blank?'':Number(a.Target),comp=blank?'':(String(a['Chiều'])==='Giảm'?(actual===0?1:target/actual):(target===0?(actual===0?1:''):actual/target)),score=comp===''?'':sscore_(comp),w=Number(a['Trọng số %']||0);supsert_(ST.RES,'ASSIGNMENT_ID',aid,{PERIOD_ID:sper_(a.PERIOD_ID),ASSIGNMENT_ID:aid,EMPLOYEE_ID:a.ASSIGNEE_ID,'Mã KPI':a['Mã KPI'],Target:target,'Thực hiện':actual,'% Hoàn thành':comp,'Điểm 1-5':score,'Trọng số %':w,'Điểm quy đổi':score===''?'':score*w/100,'Trạng thái dữ liệu':blank?'CHO_PHE_DUYET_TARGET':'DA_XAC_NHAN','Trạng thái chốt':'DANG_THUC_HIEN'})}
function sscore_(x){const c=sconfig_();return x<Number(c.SCORE_1_MAX||.7)?1:x<Number(c.SCORE_2_MAX||.85)?2:x<Number(c.SCORE_3_MAX||.95)?3:x<Number(c.SCORE_4_MAX||1)?4:5}
function supsert_(n,key,val,o){const s=sss_().getSheetByName(n),v=s.getDataRange().getValues(),h=v[0].map(String),ki=h.indexOf(key),ri=v.findIndex((r,i)=>i>0&&String(r[ki])===String(val));if(ri<0)return s.appendRow(h.map(k=>Object.prototype.hasOwnProperty.call(o,k)?o[k]:''));s.getRange(ri+1,1,1,h.length).setValues([h.map((k,i)=>Object.prototype.hasOwnProperty.call(o,k)?o[k]:v[ri][i])])}
function supdate_(n,key,val,o){return supsert_(n,key,val,o)}
function slog_(uid,a,n,id,b,af){sappend_(ST.LOG,{LOG_ID:'LOG-'+Utilities.getUuid().slice(0,8),'Thời gian':new Date(),USER_ID:uid,'Hành động':a,'Đối tượng':n,OBJECT_ID:id,'Dữ liệu trước':b,'Dữ liệu sau':af})}
