const SIMPLE_SPREADSHEET_ID='1z2vVKOAuIiDvYXzIcY4nl-vARVaTb_PC-EsWN294NeM';
const ST={EMP:'NHAN_VIEN',DEP:'PHONG_BAN',KPI:'DANH_MUC_KPI',ROLE:'KPI_THEO_VI_TRI',ASN:'GIAO_CHI_TIEU',PERF:'THUC_HIEN_KPI',RES:'KET_QUA_KPI',CFG:'CAU_HINH',LOG:'NHAT_KY_HE_THONG',P3:'CAU_HINH_3P',PAY:'BANG_LUONG'};
function doGetSimple(){return HtmlService.createTemplateFromFile('Index').evaluate().setTitle('CT Food KPI')}
function includeSimple(n){return HtmlService.createHtmlOutputFromFile(n).getContent()}
function sss_(){return SpreadsheetApp.openById(SIMPLE_SPREADSHEET_ID)}
function srows_(n){const s=sss_().getSheetByName(n);if(!s)return[];const v=s.getDataRange().getValues();if(v.length<2)return[];const h=v[0].map(String);return v.slice(1).filter(r=>r.some(x=>x!==''&&x!=null)).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]])))}
function sper_(v){return v instanceof Date?Utilities.formatDate(v,'Asia/Ho_Chi_Minh','yyyy-MM'):String(v||'')}
function sconfig_(){return Object.fromEntries(srows_(ST.CFG).map(x=>[x.KEY,x.VALUE]))}
function scurrentPeriod_(){const v=sconfig_().CURRENT_PERIOD;return sper_(v)||Utilities.formatDate(new Date(),'Asia/Ho_Chi_Minh','yyyy-MM')}
function scurrentUser_(){const e=String(Session.getActiveUser().getEmail()||'').toLowerCase();if(!e)throw Error('Không xác định được email Google. Cần triển khai Web App với quyền truy cập phù hợp Google Workspace.');const u=srows_(ST.EMP).find(x=>String(x.Email||'').toLowerCase()===e&&String(x['Trạng thái']||'ACTIVE')!=='NGHI_VIEC');if(!u)throw Error('Email '+e+' chưa có trong NHAN_VIEN');return u}
function sscope_(u,e){const r=String(u['Vai trò hệ thống']||'EMPLOYEE');return ['ADMIN','BOARD','EXECUTIVE'].includes(r)||r==='MANAGER'&&String(e.DEPARTMENT_ID)===String(u.DEPARTMENT_ID)||String(e.EMPLOYEE_ID)===String(u.EMPLOYEE_ID)}
function getSimpleAppData(){const u=scurrentUser_(),p=scurrentPeriod_(),es=srows_(ST.EMP).filter(e=>sscope_(u,e)),ids=new Set(es.map(e=>String(e.EMPLOYEE_ID))),as=srows_(ST.ASN).filter(a=>sper_(a.PERIOD_ID)===p&&ids.has(String(a.ASSIGNEE_ID))),rs=srows_(ST.RES).filter(r=>sper_(r.PERIOD_ID)===p&&ids.has(String(r.EMPLOYEE_ID))),pf=srows_(ST.PERF).filter(r=>sper_(r.PERIOD_ID)===p&&ids.has(String(r.EMPLOYEE_ID)));const done=rs.filter(x=>x['% Hoàn thành']!==''&&x['% Hoàn thành']!=null);return{user:u,period:p,employees:es,assignments:as,results:rs,performance:pf,summary:{score:rs.reduce((s,x)=>s+Number(x['Điểm quy đổi']||0),0),completion:done.length?done.reduce((s,x)=>s+Number(x['% Hoàn thành']||0),0)/done.length:0,active:as.filter(x=>String(x['Trạng thái'])!=='DA_CHOT').length,closed:as.filter(x=>String(x['Trạng thái'])==='DA_CHOT').length}}}
function saveSimplePerformance(d){const u=scurrentUser_(),a=srows_(ST.ASN).find(x=>String(x.ASSIGNMENT_ID)===String(d.assignmentId));if(!a||String(a.ASSIGNEE_ID)!==String(u.EMPLOYEE_ID))throw Error('KPI không thuộc người dùng');if(String(a['Trạng thái'])==='DA_CHOT')throw Error('KPI đã chốt');const id='PERF-'+Utilities.getUuid().slice(0,8).toUpperCase();sappend_(ST.PERF,{RECORD_ID:id,PERIOD_ID:sper_(a.PERIOD_ID),'Ngày':d.date||Utilities.formatDate(new Date(),'Asia/Ho_Chi_Minh','yyyy-MM-dd'),EMPLOYEE_ID:u.EMPLOYEE_ID,'Nhân viên':u['Họ tên'],ASSIGNMENT_ID:a.ASSIGNMENT_ID,'Mã KPI':a['Mã KPI'],'Tên KPI':a['Tên KPI'],'Giá trị thực hiện':Number(d.value),'Đơn vị':a['Đơn vị'],'Minh chứng/Link':d.evidence||'','Ghi chú':d.note||'','Trạng thái':'DA_GUI'});return{ok:true,id}}
function sappend_(n,o){const s=sss_().getSheetByName(n),h=s.getRange(1,1,1,s.getLastColumn()).getValues()[0];s.appendRow(h.map(k=>Object.prototype.hasOwnProperty.call(o,k)?o[k]:''))}
